function [accx_linear,accy_linear,accz_linear] = convert_acc_linear(accx,accy,accz,...
    roll,pitch,...
    p,q,r,...
    u,v,w)
[accx_no_g,accy_no_g,accz_no_g] = convert_acc_to_no_g(accx,accy,accz,...
    roll,pitch);

accx_linear  = accx_no_g - q.*w + r.*v;
accy_linear  = accy_no_g - r.*u + p.*w;
accz_linear  = accz_no_g - p.*v + q.*u;
end