function [pitch_motor_angle,yaw_motor_angle] = estimateMotorAnglesfromPos(target_lat,target_lon,target_alt,...
    platform_lat,platform_lon,platform_alt,...
    platform_roll,platform_pitch,platform_yaw)
% estimates motor rotation angles from positions and attitude
% yaw_motor_angle: rotation from platform z axis in xy body plane(+ clockwise)
% pitch_motor_angle: rotation from rotated platfrom y axis(+ up)

[target_azimuth,target_elevation] = estimateTargetAnglesFrom2LLA(target_lat,target_lon,target_alt,...
    platform_lat,platform_lon,platform_alt);


[~,pitch_motor_angle,yaw_motor_angle]=desired_NED_angles_to_gimbal_motor_angles...
    (target_azimuth,target_elevation,0,...
    platform_roll,platform_pitch,platform_yaw,...
    0);

end